# Plugin developed by GFelberg
# Config.yml

# language: en
# Thanks for downloading my plugin. For more plugins, dont forget to look my updates!
# If you find any bugs or ideas to the plugin, send me a message.

# language: br/pt
# Obrigado por baixar meu plugin. Para mais plugins, não esqueça de olhar as atualizações!
# Se você encontrar algum problema ou ter alguma ideia para o plugin, mande uma mensagem.	 

# Permissions

# badwords.admin : Access to the Badwords Command and the Help Page
# badwords.bypass : Access to use the banned words in the chat
# badwords.reload : Access to Reload the Plugin

# PlaceHolders

# %badwords_word_added% : Gets the specified word added to the list 
# %badwords_word_removed% : Gets the specified word removed from the list 
# %badwords_word_already% : Gets the specified word sent in the command and was already added to the list 
# %badwords_word_notlisted% : Gets the specified word sent in the command and its not in the list

# Configuration 1.0
# This configuration will display the Badwords Messages

Badwords:
  Prefix: '&b[&eBadwords&b]&r'
  Message: '&cDont use a badword!'

# Configuration 1.1
# This configuration will display the Help Page Messages

Help:
  Page: '&eShow this page'
  AddWord: '&eAdd a word to the list'
  RemoveWord: '&eRemoves a word from the list'
  ListWords: '&eList all the words from the list'
  Reload: '&eReloads the Plugin'
  
# Configuration 1.2
# This configuration will display the Words Messages

Word:
  Added: '&eThe word &b%badwords_word_added% &ehas been added to the list'
  Removed: '&eThe word &b%badwords_word_removed% &ehas been removed from the list'
  AlreadyAdded: '&cThe word &b%badwords_word_already% &calready exists in the list!'
  NotListed: '&cThe word &b%badwords_word_notlisted% &cits not in the list!' 
  
# Configuration 1.3
# This configuration will display the Banned Words List Messages

List:
  NoWords: '&cNo words found!'  
  